# Generated by Django 5.1.7 on 2025-03-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_remove_proyecto_categoria_remove_proyecto_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonio',
            old_name='contenido',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='testimonio',
            old_name='cliente',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='testimonios/'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
