# Generated by Django 5.1.7 on 2025-03-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_rename_contenido_testimonio_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(unique=True)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
